name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Cache buildroot
      id: cache-buildroot
      uses: actions/cache@v4
      with:
        path: buildroot
        key: buildroot-2025.08
    - name: Download & unpack buildroot
      if: steps.cache-buildroot.outputs.cache-hit != 'true'
      run: |
        wget -c 'https://buildroot.org/downloads/buildroot-2025.08.1.tar.xz'
        tar xf buildroot-2025.08.1.tar.xz
        mv buildroot-2025.08.1 buildroot
    - name: Build
      run: |
        cp -dp buildroot.conf buildroot/.config
        make -C buildroot -j `nproc`
    - name: Prepare artifact
      run: |
        rm -rf buildroot/output/host/i686-buildroot-linux-uclibc/sysroot/{lib/ld-uClibc.so.*,lib/ld-uClibc-*.so,lib/libc.so.*,lib/libuClibc-*.so,usr/include,usr/lib}
        tar c -C buildroot/output/host . | xz -9 > _site/cross-i586.tar.xz
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4
